# Generated by Django 4.2.6 on 2024-01-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachTournament',
            fields=[
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, null=True)),
                ('federation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('eventnummer', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('federation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('plays_beach', models.BooleanField(blank=True, null=True)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeachTeam',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('NoPlayer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoPlayer1', to='webapp.player')),
                ('NoPlayer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoPlayer2', to='webapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='BeachRound',
            fields=[
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bracket', models.CharField(blank=True, max_length=100, null=True)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('NoTournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoTournamentRound', to='webapp.beachtournament')),
            ],
        ),
        migrations.CreateModel(
            name='BeachMatch',
            fields=[
                ('No', models.IntegerField(primary_key=True, serialize=False)),
                ('NoInTournament', models.IntegerField(blank=True, null=True)),
                ('LocalDate', models.DateField(blank=True, null=True)),
                ('LocalTime', models.TimeField(blank=True, null=True)),
                ('Court', models.CharField(blank=True, max_length=100, null=True)),
                ('MatchPointsA', models.IntegerField(blank=True, null=True)),
                ('MatchPointsB', models.IntegerField(blank=True, null=True)),
                ('NoRound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoRound', to='webapp.beachround')),
                ('NoTeamA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoTeamA', to='webapp.beachteam')),
                ('NoTeamB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoTeamB', to='webapp.beachteam')),
                ('NoTournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NoTournament', to='webapp.beachtournament')),
            ],
        ),
    ]
