# Generated by Django 4.2.6 on 2023-10-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='courts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='country',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_city', to='webapp.cities'),
        ),
    ]
