# Generated by Django 4.2.6 on 2023-10-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_player_remove_matches_loser_remove_matches_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=5, null='True'),
        ),
    ]
