# Generated by Django 4.2.6 on 2023-10-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cities_remove_courts_city_remove_courts_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='courts',
            options={'verbose_name_plural': 'Courts'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='rounds',
            options={'verbose_name_plural': 'Rounds'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name_plural': 'Tournaments'},
        ),
    ]
