# Generated by Django 4.2.6 on 2024-01-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_beachtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachtournament',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
