# Generated by Django 4.2.6 on 2024-01-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
