# Generated by Django 4.2.6 on 2023-10-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_player_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='no',
            field=models.IntegerField(unique=True),
        ),
    ]
