# Generated by Django 4.2.6 on 2024-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_event_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beachmatch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='court',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='duration_set1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='duration_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='local_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='local_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='match_points_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='match_points_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_in_tournament',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_player_a1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_player_a2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_player_b1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_player_b2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_round',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_tournament',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='points_team_a_set1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='points_team_a_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='points_team_b_set1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='points_team_b_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
