# Generated by Django 4.2.6 on 2023-10-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_player_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=5),
        ),
    ]
