# Generated by Django 4.2.6 on 2024-01-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_beachmatch_match_points_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachmatch',
            name='duration_set1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='duration_set2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='duration_set3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='no_tournament',
            field=models.CharField(blank=True, null=True),
        ),
    ]
