# Generated by Django 4.2.6 on 2024-01-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_beachmatch_duration_set1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachmatch',
            name='local_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
