# Generated by Django 4.2.6 on 2024-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_beachmatch_local_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachmatch',
            name='local_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
