# Generated by Django 4.2.6 on 2023-10-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_player_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='player',
            name='version',
        ),
    ]
