# Generated by Django 4.2.6 on 2024-01-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_beachmatch_local_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachround',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
