# Generated by Django 4.2.6 on 2024-01-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_beachround_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachround',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
