# Generated by Django 4.2.6 on 2023-10-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_player_nationality_remove_player_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('earned_points_team', models.PositiveIntegerField(blank=True, null=True)),
                ('earnings_team', models.PositiveIntegerField(blank=True, null=True)),
                ('no', models.PositiveIntegerField(unique=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_as_player1', to='webapp.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_as_player2', to='webapp.player')),
            ],
            options={
                'verbose_name_plural': 'BeachTeams',
                'ordering': ['no'],
                'unique_together': {('player1', 'player2', 'version')},
            },
        ),
    ]
