# Generated by Django 4.2.6 on 2023-10-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_beachteam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beachteam',
            unique_together={('player1', 'player2', 'name')},
        ),
    ]
