# Generated by Django 4.2.6 on 2024-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_beachround_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachround',
            name='end_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='beachround',
            name='start_date',
            field=models.CharField(),
        ),
    ]
