# Generated by Django 4.2.6 on 2024-01-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_beachround_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachmatch',
            name='team_a',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='webapp.beachteam'),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='webapp.beachteam'),
        ),
    ]
