# Generated by Django 4.2.6 on 2023-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_beachteam_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachteam',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
