# Generated by Django 4.2.6 on 2024-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_beachmatch_team_a_alter_beachmatch_team_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
