# Generated by Django 4.2.6 on 2023-10-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_beachteam_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('bracket', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
        ),
    ]
